# **Experimentación TP3**

In [1]:
import numpy as np
import matplotlib as plt
import numpy.linalg as lng
from scipy.linalg import lu
from scipy import linalg
import networkx as nx
from scipy.stats.stats import pearsonr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import import_ipynb
import utils 
sns.set_style("whitegrid")

importing Jupyter notebook from utils.ipynb


Probando ejemplos

In [2]:
A = utils.leer_grafo('tests/test_aleatorio.txt')
utils.calcular_ranks('tests/test_aleatorio.txt', 0.76)

array([0.24074002, 0.21864311, 0.21864311, 0.24074002, 0.08123375])

In [3]:
G = utils.leer_grafo('tests/test_aleatorio.txt')
n = np.shape(G)[0]
cjs = utils.grados(G)
D = np.array(np.diag(cjs))
I = np.array(np.eye((n)))
R = G @ D
pR = 0.76*R
A = I - pR
col = np.array(np.ones(n))

x_init = np.random.rand(n)
x = linalg.solve(A, col)
normalized_x = (x)/np.sum(x)
normalized_x

sol, error = utils.jacobi(A, col, 10000, x_init, x)
normalized_sol = (sol)/np.sum(sol)

print(normalized_x)
print(normalized_sol)

Converge Jacobi:  True 0.5833698282254386
[0.24074002 0.21864311 0.21864311 0.24074002 0.08123375]
[0.24074002 0.21864311 0.21864311 0.24074002 0.08123375]


# GRAFOS PARTICULARES

In [4]:
def armar_grafo_supernodo(n):
  #El nodo 0 es la página supernodo que es citada por todas y los demás nodos  
    supernodo = np.array(np.zeros(n*n)).reshape(n, n) ## i en w[i][j] j->i
    for j in range(1, n):
          # todos linkean al supernodo
          supernodo[0][j] = 1
    utils.generar_archivo_test_de_matriz('test_supernodo_' + str(n) + '.txt', supernodo)
    return supernodo

In [5]:
S = armar_grafo_supernodo(10)