# **Experimentación TP3**

In [1]:
import numpy as np
import matplotlib as plt
import numpy.linalg as lng
from scipy.linalg import lu
from scipy import linalg
import networkx as nx
from scipy.stats.stats import pearsonr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import import_ipynb
import utils 
sns.set_style("whitegrid")

importing Jupyter notebook from utils.ipynb


Probando ejemplos

In [2]:
A = utils.leer_grafo('tests/test_aleatorio.txt')
utils.calcular_ranks('tests/test_aleatorio.txt', 0.76)

array([0.24074002, 0.21864311, 0.21864311, 0.24074002, 0.08123375])

In [3]:
G = utils.leer_grafo('tests/test_aleatorio.txt')
n = np.shape(G)[0]
cjs = utils.grados(G)
D = np.array(np.diag(cjs))
I = np.array(np.eye((n)))
R = G @ D
pR = 0.76*R
A = I - pR
col = np.array(np.ones(n))

x_init = np.random.rand(n)
x = linalg.solve(A, col)
normalized_x = (x)/np.sum(x)
normalized_x

sol, error = utils.jacobi(A, col, 10000, x_init, x)
normalized_sol = (sol)/np.sum(sol)

print(normalized_x)
print(normalized_sol)

Converge Jacobi:  True 0.5833698282254386
[0.24074002 0.21864311 0.21864311 0.24074002 0.08123375]
[0.24074002 0.21864311 0.21864311 0.24074002 0.08123375]


# **GRAFOS PARTICULARES**

Supernodo

In [4]:
S = utils.armar_grafo_supernodo(10)
print(S)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Antisupernodo

In [5]:
A = utils.armar_grafo_antisupernodo(10)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Supernodo al que le agregamos ejes

In [6]:
n = 10
p = 0.23
exp = utils.experimento_supernodo_le_agrego_ejes(n, p)

Anti-Supernodo al que le agregamos ejes

In [7]:
n = 10
p = 0.23
exp = utils.experimento_antisupernodo_le_agrego_ejes(n, p)

Clique

In [11]:
clique = nx.to_numpy_array(nx.complete_graph(n))
print(clique)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]
